/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuizoraApp.Ui.Auth;

/**
 *
 * @author Jeremy
 */
public class loginForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(loginForm.class.getName());

    /**
     * Creates new form loginForm
     */
    public loginForm() {
        initComponents();
        applySatoshi(getContentPane());
    }

    private void applySatoshi(java.awt.Container container) {
        try (java.io.InputStream regularStream = getClass().getResourceAsStream("/QuizoraApp/Resources/Fonts/Satoshi-Regular.ttf");
             java.io.InputStream boldStream = getClass().getResourceAsStream("/QuizoraApp/Resources/Fonts/Satoshi-Bold.ttf")) {
            java.awt.Font regular = java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, regularStream);
            java.awt.Font bold = java.awt.Font.createFont(java.awt.Font.TRUETYPE_FONT, boldStream);
            applyFont(container, regular, bold);
        } catch (java.io.IOException | java.awt.FontFormatException ex) {
            logger.log(java.util.logging.Level.WARNING, "Unable to load bundled Satoshi fonts", ex);
        }
    }

    private void applyFont(java.awt.Container container, java.awt.Font regular, java.awt.Font bold) {
        for (java.awt.Component component : container.getComponents()) {
            java.awt.Font current = component.getFont();
            if (current != null) component.setFont((current.isBold() ? bold : regular).deriveFont(current.getSize2D()));
            if (component instanceof java.awt.Container nested) applyFont(nested, regular, bold);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brandingPanel = new javax.swing.JPanel();
        panelImageLabel = new javax.swing.JLabel();
        formPanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        forgotPasswordButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        registrationPanel = new javax.swing.JPanel();
        registerPromptLabel = new javax.swing.JLabel();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quizora | Sign in");
        setResizable(false);

        panelImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizoraApp/Resources/Images/loginPanelImage.png")));
        javax.swing.GroupLayout brandingPanelLayout = new javax.swing.GroupLayout(brandingPanel);
        brandingPanel.setLayout(brandingPanelLayout);
        brandingPanelLayout.setHorizontalGroup(brandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageLabel, 500, 500, 500));
        brandingPanelLayout.setVerticalGroup(brandingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImageLabel, 500, 500, 500));

        formPanel.setBackground(new java.awt.Color(255, 255, 255));

        welcomeLabel.setFont(new java.awt.Font("Satoshi", 1, 30)); // NOI18N
        welcomeLabel.setForeground(new java.awt.Color(37, 50, 56));
        welcomeLabel.setText("Welcome back");

        subtitleLabel.setFont(new java.awt.Font("Satoshi", 0, 13)); // NOI18N
        subtitleLabel.setForeground(new java.awt.Color(104, 119, 125));
        subtitleLabel.setText("Sign in to continue your learning journey.");

        usernameLabel.setFont(new java.awt.Font("Satoshi", 1, 13)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(37, 50, 56));
        usernameLabel.setLabelFor(usernameField);
        usernameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizoraApp/Resources/Icons/UIcons/user.png")));
        usernameLabel.setText("Username or email");

        usernameField.setBackground(new java.awt.Color(247, 250, 252));
        usernameField.setFont(new java.awt.Font("Satoshi", 0, 14)); // NOI18N
        usernameField.setForeground(new java.awt.Color(37, 50, 56));
        usernameField.addActionListener(this::usernameFieldActionPerformed);

        passwordLabel.setFont(new java.awt.Font("Satoshi", 1, 13)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(37, 50, 56));
        passwordLabel.setLabelFor(passwordField);
        passwordLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QuizoraApp/Resources/Icons/UIcons/lock.png")));
        passwordLabel.setText("Password");

        passwordField.setBackground(new java.awt.Color(247, 250, 252));
        passwordField.setFont(new java.awt.Font("Satoshi", 0, 14)); // NOI18N
        passwordField.setForeground(new java.awt.Color(37, 50, 56));

        forgotPasswordButton.setForeground(new java.awt.Color(56, 121, 125));
        forgotPasswordButton.setText("Forgot password?");
        forgotPasswordButton.setBorderPainted(false);
        forgotPasswordButton.setContentAreaFilled(false);
        forgotPasswordButton.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        loginButton.setBackground(new java.awt.Color(168, 218, 220));
        loginButton.setFont(new java.awt.Font("Satoshi", 1, 14)); // NOI18N
        loginButton.setForeground(new java.awt.Color(37, 50, 56));
        loginButton.setText("Sign in");

        registrationPanel.setBackground(new java.awt.Color(255, 255, 255));

        registerPromptLabel.setForeground(new java.awt.Color(104, 119, 125));
        registerPromptLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerPromptLabel.setText("New to Quizora?");

        registerButton.setFont(new java.awt.Font("Satoshi", 1, 12)); // NOI18N
        registerButton.setForeground(new java.awt.Color(56, 121, 125));
        registerButton.setText("Create an account");
        registerButton.setBorderPainted(false);
        registerButton.setContentAreaFilled(false);

        javax.swing.GroupLayout registrationPanelLayout = new javax.swing.GroupLayout(registrationPanel);
        registrationPanel.setLayout(registrationPanelLayout);
        registrationPanelLayout.setHorizontalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(registerPromptLabel, 180, 180, 180)
                    .addComponent(registerButton, 180, 180, 180))
                .addGap(96, 96, 96))
        );
        registrationPanelLayout.setVerticalGroup(
            registrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registrationPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(registerPromptLabel, 20, 20, 20)
                .addGap(0, 0, 0)
                .addComponent(registerButton, 30, 30, 30)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeLabel, 372, 372, 372)
                    .addComponent(subtitleLabel, 372, 372, 372)
                    .addComponent(usernameLabel, 372, 372, 372)
                    .addComponent(usernameField, 372, 372, 372)
                    .addComponent(passwordLabel, 372, 372, 372)
                    .addComponent(passwordField, 372, 372, 372)
                    .addComponent(forgotPasswordButton, 372, 372, 372)
                    .addComponent(loginButton, 372, 372, 372)
                    .addComponent(registrationPanel))
                .addGap(64, 64, 64))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(welcomeLabel, 40, 40, 40)
                .addGap(3, 3, 3)
                .addComponent(subtitleLabel, 22, 22, 22)
                .addGap(25, 25, 25)
                .addComponent(usernameLabel, 20, 20, 20)
                .addGap(7, 7, 7)
                .addComponent(usernameField, 42, 42, 42)
                .addGap(17, 17, 17)
                .addComponent(passwordLabel, 20, 20, 20)
                .addGap(7, 7, 7)
                .addComponent(passwordField, 42, 42, 42)
                .addGap(2, 2, 2)
                .addComponent(forgotPasswordButton, 32, 32, 32)
                .addGap(10, 10, 10)
                .addComponent(loginButton, 44, 44, 44)
                .addGap(15, 15, 15)
                .addComponent(registrationPanel)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(brandingPanel)
                .addGap(0, 0, 0)
                .addComponent(formPanel))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(brandingPanel)
            .addComponent(formPanel)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new loginForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel brandingPanel;
    private javax.swing.JButton forgotPasswordButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JLabel registerPromptLabel;
    private javax.swing.JPanel registrationPanel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JTextField usernameField;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JLabel panelImageLabel;
    // End of variables declaration//GEN-END:variables
}
